"""empty message

Revision ID: 057d55f833a1
Revises: 08a3a50da21d
Create Date: 2026-01-22 16:51:42.566289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057d55f833a1'
down_revision: Union[str, Sequence[str], None] = '08a3a50da21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'path')
    # ### end Alembic commands ###
