"""empty message

Revision ID: 0aa633ef89aa
Revises: 057d55f833a1
Create Date: 2026-01-22 16:58:06.912522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa633ef89aa'
down_revision: Union[str, Sequence[str], None] = '057d55f833a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
