"""make_image_path_required

Revision ID: 5cbf6c93c5d1
Revises: 0aa633ef89aa
Create Date: 2026-01-22 16:58:36.275919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbf6c93c5d1'
down_revision: Union[str, Sequence[str], None] = '0aa633ef89aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
